name: ttml_parser
description: "A Flutter package for parsing TTML (Timed Text Markup Language) lyric files."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/heart_sutra.ttml